// api/news-chat.js
export default async function handler(req, res) {
  // CORS for GitHub Pages
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      return res.status(500).json({
        error: "OPENAI_API_KEY is not set in Vercel env vars",
      });
    }

    const { question, articles } = req.body || {};
    if (!question || !Array.isArray(articles)) {
      return res.status(400).json({
        error: "Body must include 'question' (string) and 'articles' (array)",
      });
    }

    const limitedArticles = articles.slice(0, 15).map((a, idx) => ({
      index: idx,
      title: a.title || "",
      description: a.description || "",
      category: a.category || "",
      source: a.source || "",
      url: a.url || "",
    }));

    const userPrompt = `
You are a calm, concise news assistant for a personal dashboard.

You receive:
- A list of recent news articles (title, brief description, category, source, URL)
- A question from the user

Rules:
- Only use information that could reasonably come from these articles.
- If the user asks about something outside this feed, say you only know about "today's feed on this page".
- Prefer 3–6 short bullet points or a short paragraph.
- Mention source names naturally (e.g. Indian Express, TechCrunch) when helpful.
- Keep the tone calm, slightly optimistic, not sensational.

User question:
"${question}"

Articles:
${JSON.stringify(limitedArticles, null, 2)}
    `.trim();

    const openaiRes = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4.1-mini",
        messages: [
          {
            role: "system",
            content:
              "You are a calm, structured assistant for summarising a news feed. Keep answers short and grounded in the provided articles.",
          },
          {
            role: "user",
            content: userPrompt,
          },
        ],
      }),
    });

    if (!openaiRes.ok) {
      const txt = await openaiRes.text();
      console.error("OpenAI chat error:", openaiRes.status, txt);
      return res.status(500).json({
        error: "OpenAI API error",
        status: openaiRes.status,
      });
    }

    const data = await openaiRes.json();
    const answer = data.choices?.[0]?.message?.content?.trim();

    if (!answer) {
      return res.status(500).json({
        error: "No answer generated by OpenAI",
      });
    }

    return res.status(200).json({ answer });
  } catch (err) {
    console.error("Error in /api/news-chat:", err);
    return res.status(500).json({
      error: "Internal server error in /api/news-chat",
    });
  }
}
